---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: marvelapi-dpl
spec:
  selector:
    matchLabels:
      app: marvelapi
      env: production
  replicas: 3
  template:
    metadata:
      labels:
        app: marvelapi
        env: production
    spec:
      containers:
        - name: marvel-api
          image: marvel-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: app.settings.production
          resources:
            limits:
              memory: "2000Mi"
              cpu: "2000m"
            requests:
              memory: "2000Mi"
              cpu: "2000m"

---
apiVersion: v1
kind: Service
metadata:
  name: marvelapi-svc
  namespace: marvelapi
spec:
  type: LoadBalancer
  selector:
    app: marvelapi
    env: production
  ports:
    - port: 80
      targetPort: 8000