---
apiVersion: v1
kind: Service
metadata:
  name: marvelapi-svc
  namespace: marvelapi
spec:
  type: LoadBalancer
  selector:
    app: marvelapi
    env: production
  ports:
    - port: 80
      targetPort: 80